/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mess.finder;

import java.awt.HeadlessException;
import java.sql.*;
import java.awt.print.PrinterException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author hp1
 */
public class M15 extends javax.swing.JFrame {

    /**
     * Creates new form M15
     */
    public M15() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(10, 150, 220, 40);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 51, 255));
        jButton1.setText("PAY BILL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(360, 430, 117, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("REGISTERED PHONE NO");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 110, 230, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se.gif"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(230, 150, 120, 40);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 460, 160, 60);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 320, 330, 40);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 250, 200, 30);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(220, 260, 110, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 360, 310, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(480, 500, 90, 30);

        jLabel6.setBackground(new java.awt.Color(204, 255, 255));
        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 200, 140, 50);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 410, 320, 30);

        jButton4.setBackground(new java.awt.Color(51, 255, 153));
        jButton4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 0, 255));
        jButton4.setText("PRINT RECIPT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(560, 430, 180, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/master_card-512.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 0, 300, 100);

        jTextArea1.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(350, 0, 400, 410);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LI.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-6, 0, 760, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        // TODO add your handling code here:
        int m=JOptionPane.showConfirmDialog(null,"YOU WANT TO PAY THE BILL");
       
  if(m==0)
  {
      jTextArea1.setText("******************************************\n");
      jTextArea1.setText(jTextArea1.getText()+"*        PAYMENT RECEIPT         *\n");
      jTextArea1.setText(jTextArea1.getText()+"******************************************\n");
      
      Date obj = new Date();
      String date = obj.toString();
      jTextArea1.setText(jTextArea1.getText()+"\n"+date+"\n\n");
      jTextArea1.setText(jTextArea1.getText()+"REGISTERED PHONE NUMBER:"+jTextField1.getText()+"\n\n");
      jTextArea1.setText(jTextArea1.getText()+"MESS NAME:"+jLabel7.getText()+"\n\n");
      jTextArea1.setText(jTextArea1.getText()+"MESS PRODUCT KEY:"+jLabel10.getText()+"\n\n");
      jTextArea1.setText(jTextArea1.getText()+"QUANTITY OF PLATES ORDER:"+jLabel8.getText()+"\n\n");
      jTextArea1.setText(jTextArea1.getText()+"PAYMENT AMOUNT RS:"+jLabel9.getText()+"\n\n");
      jTextArea1.setText(jTextArea1.getText()+"\n                                SIGNATURE");
        }
  else
  {
      JOptionPane.showMessageDialog(null,"");
  }
  
        
         
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String mobilenumber=jTextField1.getText();
        if(mobilenumber.matches("^[0-9]*$") && mobilenumber.length()==10)
        {
        jLabel6.setText("MESS NAME");
        jLabel2.setText("TOTAL NO OF PLATES ORDERED");
        jLabel3.setText("TOTAL AMOUNT");
        
          try
        {
             Class.forName("java.sql.Driver");
             java.sql.Connection con=DriverManager.getConnection("jdbc:mysql://localhost/present","root","mysql");
             Statement st=con.createStatement();
              String qu = "select * from ordernow where phonenumber= ?";
              PreparedStatement pstmt=con.prepareStatement(qu);
              pstmt.setString(1,(jTextField1.getText()));
              
              ResultSet rs=pstmt.executeQuery();
              if(rs.next())
              {
                   jLabel7.setText(rs.getString("mname"));
                   jLabel10.setText(rs.getString("messpk"));
                   jLabel8.setText(rs.getString("quantity"));
                   jLabel9.setText(rs.getString("tprice"));
              }
              else
              {
                   st.executeUpdate(qu);
                  JOptionPane.showMessageDialog(null,"record not found");
              }
           st.close();
          con.close();
             
        }
         catch(HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e)
         {
             JOptionPane.showMessageDialog(null,"NO SUCH RECORD FOUND");
         }
        }
        else
        {
             JOptionPane.showMessageDialog(null,"PLEASE ENTER VALID PHONE NUMBER");
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int m=JOptionPane.showConfirmDialog(null,"YOU WANT TO PRINT THE BILL");
       
  if(m==0) 
  {
        try{
            boolean print = jTextArea1.print();
        }
        catch(PrinterException e)
        {
            
        }
  }
  else
  {
      JOptionPane.showMessageDialog(null,"");
  }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(M15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(M15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(M15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(M15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new M15().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
