/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mess.finder;

/**
 *
 * @author hp1
 */
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
public class M16 extends javax.swing.JFrame {

    boolean type = false;
    int quauntity = 0;
    int price  = 0;
    int totalprice = 0;
    String messname = null;
    String mobile = null;
    
    
    public M16() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png-clipart-plus-and-minus-signs-plus-minus-sign-meno-symbol-subtraction-symbol-miscellaneous-rectangle.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(230, 250, 50, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (400).png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 110, 200, 100);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Plus_Sign-512.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(370, 250, 50, 50);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(300, 250, 50, 50);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(470, 480, 150, 50);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(20, 480, 270, 50);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(420, 70, 210, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se.gif"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(350, 130, 110, 50);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(220, 130, 130, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rupee-currency-symbol-on-round-sticker-with-blue-vector-28044702.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(400, 480, 70, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (402).png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 370, 201, 90);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/R.jpg"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(470, 250, 130, 40);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(50, 570, 40, 40);

        jLabel6.setBackground(new java.awt.Color(51, 51, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ENTER YOUR MOBILE NUMBER");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 70, 370, 30);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(470, 570, 73, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (403).png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(410, 360, 200, 100);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/order-now-button-order-now-rounded-red-sign-order-vector-27111642.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(250, 570, 120, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (401).png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 230, 200, 100);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Order food online & Eat Good, Eat Exciting!");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 670, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(type==true){
            quauntity--;
            //  plus
            if(quauntity>=0){
                String p =  String.valueOf(quauntity);
            jTextField2.setText(p);
            totalprice = totalprice-price;
            jTextField3.setText(totalprice+" ");
            }
            else{
                quauntity = 0;
                jTextField3.setText("0");
                jTextField2.setText("0");
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Enter the mess product id first");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(type==true){
            quauntity++;
            //  plus
            String p =  String.valueOf(quauntity);
            jTextField2.setText(p);
            totalprice = price+totalprice;
            jTextField3.setText(totalprice+" ");
        }
        else{
            JOptionPane.showMessageDialog(null,"Enter the mess product id first");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         try
        {
             Class.forName("java.sql.Driver");
             java.sql.Connection con=DriverManager.getConnection("jdbc:mysql://localhost/present","root","mysql");
             Statement st=con.createStatement();
              String qu="INSERT INTO ordernow VALUES('"+jTextField5.getText()+"','"+jTextField1.getText()+"','"+jTextField4.getText()+"','"+jTextField2.getText()+"','"+jTextField3.getText()+"');";
               {
                st.executeUpdate(qu);
                JOptionPane.showConfirmDialog(null,"DO YOU WANT TO PLACE THE ORDER ");
                dispose();
                new M16().setVisible(true);
 }
               st.close();
          con.close();
             
        }
         catch(HeadlessException | ClassNotFoundException | SQLException e)
         {
             JOptionPane.showMessageDialog(null,"error unable to get connected"+e);
         }       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String id = jTextField1.getText();
       String phone=jTextField4.getText();
       int yo=0;
     if(phone.matches("^[0-9]*$") && phone.length()==10)  
     {
       if(id!=null)
       {
           boolean check = true;
           for(int i=0;i<id.length();i++)
            {
               if(id.charAt(i)>='0' && id.charAt(i)<='9'){
                   check = true;
               }
               else
               {
                   check = false;
                   break;
               }
            }
           if(check==true){
           
                int ID = Integer.parseInt(id);
                type = true;
                if(ID==7882)
                {
                      jTextField5.setText("ANAPURANA MESS");
                      price = 50;
                }
                if(ID==5454)
                {
                      jTextField5.setText("ANJANA MESS");
                      price = 60;
                }
                if(ID==6678)
                {
                      jTextField5.setText("GOKUL MESS");
                      price = 40;
                }
                if(ID==5678)
                {
                     jTextField5.setText("MOMS KITCHEN");
                     price = 70;
                }
                if(ID==8976)
                {
                     jTextField5.setText("PATHAK MESS");
                     price = 60;
                }
                jTextField2.setText("0");
                jTextField3.setText("0");
                
           }
           else{
               JOptionPane.showMessageDialog(null,"Something went wrong check mess id");
           }
       }
       else
       {
           JOptionPane.showMessageDialog(null,"Something went wrong check mess id");
       }
     }
     else
     {
         JOptionPane.showMessageDialog(null,"INVALID PHONE NUMBER");
     }
     
       
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(" ");
         jTextField2.setText(" ");
          jTextField3.setText(" ");
           jTextField4.setText(" ");
            jTextField5.setText(" ");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new M7().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(M16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(M16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(M16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(M16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new M16().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
