/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mess.finder;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author hp1
 */
public class M6 extends javax.swing.JFrame {

    /**
     * Creates new form M6
     */
    public M6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 550));

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (378).png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 0, 280, 140);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(240, 250, 150, 35);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/R.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(440, 250, 150, 50);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(60, 350, 140, 40);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(60, 420, 140, 40);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(250, 350, 150, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E.jpg"))); // NOI18N
        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(570, 0, 70, 30);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(250, 420, 150, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(0, 0, 50, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(393, 170, 70, 50);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(450, 350, 160, 40);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(450, 420, 160, 40);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(250, 300, 150, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(190, 170, 210, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AF-Client-Login-background-1024x682 (1).png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(3, -11, 640, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          try
        { 
             Class.forName("java.sql.Driver");
              try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost/present","root","mysql")) {
                  Statement st=con.createStatement();
                  String qu = "select * from messdetails where mess_id= ?";
                  PreparedStatement pstmt=con.prepareStatement(qu);
                  pstmt.setString(1,jTextField1.getText());
                  ResultSet rs=pstmt.executeQuery();
                  if(rs.next())
                  {
                      
                      jTextField2.setText(rs.getString("date"));
                      jTextField3.setText(rs.getString("m1"));
                      jTextField4.setText(rs.getString("m2"));
                      jTextField5.setText(rs.getString("m3"));
                      jTextField6.setText(rs.getString("m4"));
                      jTextField8.setText(rs.getString("m5"));
                      jTextField7.setText(rs.getString("m6"));
                      
                  }
                  else
                  {
                      st.executeUpdate(qu);
                      JOptionPane.showMessageDialog(null,"record not found");
                  }
                  st.close();
              }
             
        }
         catch(HeadlessException | ClassNotFoundException | SQLException e)
         {
             JOptionPane.showMessageDialog(null,"NO SUCH RECORD FOUND");
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String temp = jTextField2.getText();
        boolean check = true;
        if(temp.length()==10)
        {
            for(int i  = 0;i<temp.length();i++)
            {
                if(i!=2 && i!=5)
                {
                   if(temp.charAt(i)>='0' && temp.charAt(i)<='9')
                    {
                        
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Invalid date of birtth");
                        check = false;
                        break;
                    }
                }
            }
            if(check==true && temp.charAt(2)=='/' && temp.charAt(5)=='/')
            {
                 try
        {
             Class.forName("java.sql.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost/present","root","mysql")) {
                String sql="update messdetails set m1=?,m2=?,m3=?,m4=?,m5=?,m6=?,date=? where mess_id=?";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1, jTextField3.getText());
                pstmt.setString(2, jTextField4.getText());
                pstmt.setString(3, jTextField5.getText());
                pstmt.setString(4, jTextField6.getText());
                pstmt.setString(5, jTextField7.getText());
                pstmt.setString(6, jTextField8.getText());
                
                pstmt.setString(7, jTextField2.getText());
                pstmt.setString(8, jTextField1.getText());
                
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, " UPDATED SUCCESSFULLY DONE");
            }
            }
         catch(HeadlessException | ClassNotFoundException | SQLException e)
         {
             JOptionPane.showMessageDialog(null,e);
         }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "PLEASE ENTER CORRECT DOB");
       
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "PLEASE ENTER CORRECT DOB");
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(" ");
        jTextField2.setText(" ");
        jTextField3.setText(" ");
        jTextField4.setText(" ");
        jTextField5.setText(" ");
        jTextField6.setText(" ");
        jTextField7.setText(" ");
        jTextField8.setText(" ");
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         new MF().setVisible(true);
         dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(M6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(M6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(M6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(M6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new M6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
