/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mess.finder;

/**
 *
 * @author hp1
 */
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
public class MF2 extends javax.swing.JFrame {

    /**
     * Creates new form MF2
     */
    public MF2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FEMALE = new javax.swing.JRadioButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        MALE = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/name.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 220, 69);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(320, 60, 290, 60);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(330, 140, 240, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gender.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 200, 150, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DOB.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 140, 150, 50);

        buttonGroup1.add(FEMALE);
        FEMALE.setText("FEMALE");
        jPanel1.add(FEMALE);
        FEMALE.setBounds(360, 260, 100, 23);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(340, 310, 220, 60);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(320, 380, 250, 110);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 500, 140, 70);

        buttonGroup1.add(MALE);
        MALE.setText("MALE");
        jPanel1.add(MALE);
        MALE.setBounds(360, 200, 100, 23);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password.jpg"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 580, 150, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(530, 640, 70, 40);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(320, 500, 250, 60);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(200, 630, 250, 60);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(0, 0, 40, 40);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(320, 570, 250, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/R.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 650, 100, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/address.jpg"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 380, 75, 110);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 51));
        jLabel10.setText("DD/MM/YYYY");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(210, 160, 110, 22);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 51));
        jLabel11.setText(" WRITE@aakk ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(190, 500, 110, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phone number.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 310, 70, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sign-up-.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 0, 200, 54);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp1\\Downloads\\java p\\o3.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(4, -6, 620, 840);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(470, 200, 87, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        boolean check = true;
        String temp = jTextField5.getText();
        String tem = jTextField2.getText();
        String tempp = jTextField3.getText();
        if(tem.length()==10)
        {
            if(tem.charAt(2)!='/' || tem.charAt(5)!='/' ){
             check = false;   
              JOptionPane.showMessageDialog(null,"Invalid date of birthhh");
            }
            for(int i = 0 ;i<tem.length();i++){
                if(i!=2 && i!=5)
                {
                    if(tem.charAt(i)>='0' && tem.charAt(i)<='9')
                    {
                        
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Invalid date of birtth");
                        check = false;
                        break;
                    }
                }
            }
        }
        else
        {
            check = false;
              JOptionPane.showMessageDialog(null,"Invalidd date of birth");
        }
        if(check==true){
            if(tempp.matches("^[0-9]*$") && tempp.length()==10 )
            {
                
            }
            
            else{
                    JOptionPane.showMessageDialog(null,"Invalid PHONE NUMBER");
                    check = false;
                  }
                
            
            if(check==true)
            {
        if(temp.contains("@aakk")==false || temp.length()<=5 || temp.charAt(0)=='@'){
            JOptionPane.showMessageDialog(null,"Invalid email address");
            check=false;
        }
        if(check==true)
        {
            
        
        try
        {
               Class.forName("java.sql.Driver");
              try (java.sql.Connection con = DriverManager.getConnection( "jdbc:mysql://localhost/present","root","mysql")) {
                String qu="INSERT INTO signupmess VALUES (?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement pstmt=con.prepareStatement(qu);
                pstmt.setString(1,jTextField1.getText());
                pstmt.setString(2,jTextField2.getText());
                String gender = null;
                if(MALE.isSelected())
                {
                    gender=MALE.getText();
                }
                if(FEMALE.isSelected())
                {
                    gender=FEMALE.getText();
                }
                pstmt.setString(3, gender);
                pstmt.setString(4,jTextField3.getText());
                pstmt.setString(5,jTextField4.getText());
                pstmt.setString(6,jTextField5.getText());
                pstmt.setString(7,jTextField6.getText());
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null,"DETAILS ARE SUCCESSFULLY REGISTERED PLEASE GO TO LOGIN PAGE");
                new MF3().setVisible(true);
                dispose();
            }
              
             
         }
         catch(HeadlessException | ClassNotFoundException | SQLException e)
         {
             JOptionPane.showMessageDialog(null,e);
         }
        }
        }
            else
            {
                 JOptionPane.showMessageDialog(null,"something went wrong");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        buttonGroup1.clearSelection();
        jTextField1.setText(" ");
        jTextField2.setText(" ");
        jTextField3.setText(" ");
        jTextField4.setText(" ");
        jTextField5.setText(" ");
        jTextField6.setText(" ");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
     new SIGNUP().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new MF().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MF2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MF2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MF2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MF2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MF2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FEMALE;
    private javax.swing.JRadioButton MALE;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
